kind: Service
apiVersion: v1
metadata:
  name: students-app
  namespace: test
  labels:
    app: students-app
spec:
  ports:
    - nodePort: 31010
      port: 8080
      targetPort: 8080
      
  selector:
    app: students-app
  type: LoadBalancer


---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
  namespace: test
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  
---
# PVC for student-app
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: students-app-pv-claim 
  namespace: test
  labels:
    app: students-app
spec:
  accessModes:
    - ReadWriteOnce   
  resources:
    requests:
      storage: 1Gi  
  storageClassName: "fast" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: students-app
 namespace: test
 labels:
   app: students-app
spec:
  selector:
    matchLabels:
      app: students-app
  replicas: 3
  template:
    metadata:
      labels:
        app: students-app
    spec:
      containers:
        - name: students-app
          image: himanshu1018/finalcapstone:latest
          
      
          ports:
            - containerPort: 8080
          env:   
            - name: DB_HOST   
              valueFrom:
                configMapKeyRef:
                  name: db-config  
                  key: host
            - name: DB_NAME  
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: name
            - name: DB_USERNAME  
              valueFrom:
                secretKeyRef:
                  name: db-user 
                  key: username
            - name: DB_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: password
          volumeMounts:        
            - name: mystudents-app-persistent-storage
              mountPath: /var/lib/mnt 
      volumes:
        - name: mystudents-app-persistent-storage 
          persistentVolumeClaim:
            claimName: students-app-pv-claim
